export const ADD_TRAKT_PEOPLE_SUMMARY = 'ADD_TRAKT_PEOPLE_SUMMARY';
export const ADD_TMDB_PEOPLE_DETAILS = 'ADD_TMDB_PEOPLE_DETAILS';
export const ADD_TRAKT_TMDB_COMBINED_CREDITS =
  'ADD_TRAKT_TMDB_COMBINED_CREDITS';
export const ADD_TMDB_PEOPLE_EXTERNAL_IDS = 'ADD_TMDB_PEOPLE_EXTERNAL_IDS';
export const ADD_TMDB_PEOPLE_TAGGED_IMAGES = 'ADD_TMDB_PEOPLE_TAGGED_IMAGES';
export const ADD_TMDB_PEOPLE_POPULAR = 'ADD_TMDB_PEOPLE_POPULAR';
