export const ADD_TMDB_PEOPLE_BATCHED_DATA = 'ADD_TMDB_PEOPLE_BATCHED_DATA';

export const ADD_TMDB_PEOPLE_EXTERNAL_IDS = 'ADD_TMDB_PEOPLE_EXTERNAL_IDS';
export const ADD_TMDB_PEOPLE_IMAGES = 'ADD_TMDB_PEOPLE_IMAGES';
export const ADD_TMDB_PEOPLE_COMBINED_CREDITS =
  'ADD_TMDB_PEOPLE_COMBINED_CREDITS';
