export const TMDB_SEARCH_MULTI_FETCHING = 'TMDB_SEARCH_MULTI_FETCHING';
export const TMDB_SEARCH_MULTI_FETCHED = 'TMDB_SEARCH_MULTI_FETCHED';
export const TMDB_SEARCH_MULTI_WAITING = 'TMDB_SEARCH_MULTI_WAITING';
export const TMDB_SEARCH_MULTI_ERROR = 'TMDB_SEARCH_MULTI_ERROR';
