export const TMDB_SEARCH_MUTLI_FETCHING = 'TMDB_SEARCH_MUTLI_FETCHING';
export const TMDB_SEARCH_MUTLI_FETCHED = 'TMDB_SEARCH_MUTLI_FETCHED';
export const TMDB_SEARCH_MUTLI_WAITING = 'TMDB_SEARCH_MUTLI_WAITING';
export const TMDB_SEARCH_MUTLI_ERROR = 'TMDB_SEARCH_MUTLI_ERROR';
